/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingRouteRouteImport } from './routes/setting/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as SettingProfileRouteImport } from './routes/setting/profile'
import { Route as SettingIndustryRouteImport } from './routes/setting/industry'
import { Route as SettingExportRouteImport } from './routes/setting/export'
import { Route as SettingCategoriesRouteImport } from './routes/setting/categories'
import { Route as SettingCatalogsRouteImport } from './routes/setting/catalogs'
import { Route as SettingAppearanceRouteImport } from './routes/setting/appearance'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as appIndustryRouteRouteImport } from './routes/(app)/industry/route'
import { Route as appIndustryIndexRouteImport } from './routes/(app)/industry/index'
import { Route as appInventoryListRouteImport } from './routes/(app)/inventory/list'
import { Route as appInventoryEditRouteImport } from './routes/(app)/inventory/edit'
import { Route as appInventoryAddRouteImport } from './routes/(app)/inventory/add'

const SettingRouteRoute = SettingRouteRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const SettingProfileRoute = SettingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingIndustryRoute = SettingIndustryRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingExportRoute = SettingExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingCategoriesRoute = SettingCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingCatalogsRoute = SettingCatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingAppearanceRoute = SettingAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const appIndustryRouteRoute = appIndustryRouteRouteImport.update({
  id: '/industry',
  path: '/industry',
  getParentRoute: () => appRouteRoute,
} as any)
const appIndustryIndexRoute = appIndustryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appIndustryRouteRoute,
} as any)
const appInventoryListRoute = appInventoryListRouteImport.update({
  id: '/inventory/list',
  path: '/inventory/list',
  getParentRoute: () => appRouteRoute,
} as any)
const appInventoryEditRoute = appInventoryEditRouteImport.update({
  id: '/inventory/edit',
  path: '/inventory/edit',
  getParentRoute: () => appRouteRoute,
} as any)
const appInventoryAddRoute = appInventoryAddRouteImport.update({
  id: '/inventory/add',
  path: '/inventory/add',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/setting': typeof SettingRouteRouteWithChildren
  '/industry': typeof appIndustryRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/setting/appearance': typeof SettingAppearanceRoute
  '/setting/catalogs': typeof SettingCatalogsRoute
  '/setting/categories': typeof SettingCategoriesRoute
  '/setting/export': typeof SettingExportRoute
  '/setting/industry': typeof SettingIndustryRoute
  '/setting/profile': typeof SettingProfileRoute
  '/': typeof appIndexRoute
  '/inventory/add': typeof appInventoryAddRoute
  '/inventory/edit': typeof appInventoryEditRoute
  '/inventory/list': typeof appInventoryListRoute
  '/industry/': typeof appIndustryIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/setting': typeof SettingRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/setting/appearance': typeof SettingAppearanceRoute
  '/setting/catalogs': typeof SettingCatalogsRoute
  '/setting/categories': typeof SettingCategoriesRoute
  '/setting/export': typeof SettingExportRoute
  '/setting/industry': typeof SettingIndustryRoute
  '/setting/profile': typeof SettingProfileRoute
  '/': typeof appIndexRoute
  '/inventory/add': typeof appInventoryAddRoute
  '/inventory/edit': typeof appInventoryEditRoute
  '/inventory/list': typeof appInventoryListRoute
  '/industry': typeof appIndustryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/setting': typeof SettingRouteRouteWithChildren
  '/(app)/industry': typeof appIndustryRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/setting/appearance': typeof SettingAppearanceRoute
  '/setting/catalogs': typeof SettingCatalogsRoute
  '/setting/categories': typeof SettingCategoriesRoute
  '/setting/export': typeof SettingExportRoute
  '/setting/industry': typeof SettingIndustryRoute
  '/setting/profile': typeof SettingProfileRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/inventory/add': typeof appInventoryAddRoute
  '/(app)/inventory/edit': typeof appInventoryEditRoute
  '/(app)/inventory/list': typeof appInventoryListRoute
  '/(app)/industry/': typeof appIndustryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/setting'
    | '/industry'
    | '/auth/login'
    | '/auth/register'
    | '/setting/appearance'
    | '/setting/catalogs'
    | '/setting/categories'
    | '/setting/export'
    | '/setting/industry'
    | '/setting/profile'
    | '/'
    | '/inventory/add'
    | '/inventory/edit'
    | '/inventory/list'
    | '/industry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/setting'
    | '/auth/login'
    | '/auth/register'
    | '/setting/appearance'
    | '/setting/catalogs'
    | '/setting/categories'
    | '/setting/export'
    | '/setting/industry'
    | '/setting/profile'
    | '/'
    | '/inventory/add'
    | '/inventory/edit'
    | '/inventory/list'
    | '/industry'
  id:
    | '__root__'
    | '/(app)'
    | '/auth'
    | '/setting'
    | '/(app)/industry'
    | '/auth/login'
    | '/auth/register'
    | '/setting/appearance'
    | '/setting/catalogs'
    | '/setting/categories'
    | '/setting/export'
    | '/setting/industry'
    | '/setting/profile'
    | '/(app)/'
    | '/(app)/inventory/add'
    | '/(app)/inventory/edit'
    | '/(app)/inventory/list'
    | '/(app)/industry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SettingRouteRoute: typeof SettingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/setting/profile': {
      id: '/setting/profile'
      path: '/profile'
      fullPath: '/setting/profile'
      preLoaderRoute: typeof SettingProfileRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/industry': {
      id: '/setting/industry'
      path: '/industry'
      fullPath: '/setting/industry'
      preLoaderRoute: typeof SettingIndustryRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/export': {
      id: '/setting/export'
      path: '/export'
      fullPath: '/setting/export'
      preLoaderRoute: typeof SettingExportRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/categories': {
      id: '/setting/categories'
      path: '/categories'
      fullPath: '/setting/categories'
      preLoaderRoute: typeof SettingCategoriesRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/catalogs': {
      id: '/setting/catalogs'
      path: '/catalogs'
      fullPath: '/setting/catalogs'
      preLoaderRoute: typeof SettingCatalogsRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/appearance': {
      id: '/setting/appearance'
      path: '/appearance'
      fullPath: '/setting/appearance'
      preLoaderRoute: typeof SettingAppearanceRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(app)/industry': {
      id: '/(app)/industry'
      path: '/industry'
      fullPath: '/industry'
      preLoaderRoute: typeof appIndustryRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/industry/': {
      id: '/(app)/industry/'
      path: '/'
      fullPath: '/industry/'
      preLoaderRoute: typeof appIndustryIndexRouteImport
      parentRoute: typeof appIndustryRouteRoute
    }
    '/(app)/inventory/list': {
      id: '/(app)/inventory/list'
      path: '/inventory/list'
      fullPath: '/inventory/list'
      preLoaderRoute: typeof appInventoryListRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/inventory/edit': {
      id: '/(app)/inventory/edit'
      path: '/inventory/edit'
      fullPath: '/inventory/edit'
      preLoaderRoute: typeof appInventoryEditRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/inventory/add': {
      id: '/(app)/inventory/add'
      path: '/inventory/add'
      fullPath: '/inventory/add'
      preLoaderRoute: typeof appInventoryAddRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appIndustryRouteRouteChildren {
  appIndustryIndexRoute: typeof appIndustryIndexRoute
}

const appIndustryRouteRouteChildren: appIndustryRouteRouteChildren = {
  appIndustryIndexRoute: appIndustryIndexRoute,
}

const appIndustryRouteRouteWithChildren =
  appIndustryRouteRoute._addFileChildren(appIndustryRouteRouteChildren)

interface appRouteRouteChildren {
  appIndustryRouteRoute: typeof appIndustryRouteRouteWithChildren
  appIndexRoute: typeof appIndexRoute
  appInventoryAddRoute: typeof appInventoryAddRoute
  appInventoryEditRoute: typeof appInventoryEditRoute
  appInventoryListRoute: typeof appInventoryListRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndustryRouteRoute: appIndustryRouteRouteWithChildren,
  appIndexRoute: appIndexRoute,
  appInventoryAddRoute: appInventoryAddRoute,
  appInventoryEditRoute: appInventoryEditRoute,
  appInventoryListRoute: appInventoryListRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SettingRouteRouteChildren {
  SettingAppearanceRoute: typeof SettingAppearanceRoute
  SettingCatalogsRoute: typeof SettingCatalogsRoute
  SettingCategoriesRoute: typeof SettingCategoriesRoute
  SettingExportRoute: typeof SettingExportRoute
  SettingIndustryRoute: typeof SettingIndustryRoute
  SettingProfileRoute: typeof SettingProfileRoute
}

const SettingRouteRouteChildren: SettingRouteRouteChildren = {
  SettingAppearanceRoute: SettingAppearanceRoute,
  SettingCatalogsRoute: SettingCatalogsRoute,
  SettingCategoriesRoute: SettingCategoriesRoute,
  SettingExportRoute: SettingExportRoute,
  SettingIndustryRoute: SettingIndustryRoute,
  SettingProfileRoute: SettingProfileRoute,
}

const SettingRouteRouteWithChildren = SettingRouteRoute._addFileChildren(
  SettingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SettingRouteRoute: SettingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
