/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingRouteRouteImport } from './routes/setting/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as SettingProfileRouteImport } from './routes/setting/profile'
import { Route as SettingExportRouteImport } from './routes/setting/export'
import { Route as SettingCategoriesRouteImport } from './routes/setting/categories'
import { Route as SettingAppearanceRouteImport } from './routes/setting/appearance'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as appProductListRouteImport } from './routes/(app)/product/list'
import { Route as appProductAddRouteImport } from './routes/(app)/product/add'

const SettingRouteRoute = SettingRouteRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const SettingProfileRoute = SettingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingExportRoute = SettingExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingCategoriesRoute = SettingCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingRouteRoute,
} as any)
const SettingAppearanceRoute = SettingAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const appProductListRoute = appProductListRouteImport.update({
  id: '/product/list',
  path: '/product/list',
  getParentRoute: () => appRouteRoute,
} as any)
const appProductAddRoute = appProductAddRouteImport.update({
  id: '/product/add',
  path: '/product/add',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/setting': typeof SettingRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/setting/appearance': typeof SettingAppearanceRoute
  '/setting/categories': typeof SettingCategoriesRoute
  '/setting/export': typeof SettingExportRoute
  '/setting/profile': typeof SettingProfileRoute
  '/': typeof appIndexRoute
  '/product/add': typeof appProductAddRoute
  '/product/list': typeof appProductListRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/setting': typeof SettingRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/setting/appearance': typeof SettingAppearanceRoute
  '/setting/categories': typeof SettingCategoriesRoute
  '/setting/export': typeof SettingExportRoute
  '/setting/profile': typeof SettingProfileRoute
  '/': typeof appIndexRoute
  '/product/add': typeof appProductAddRoute
  '/product/list': typeof appProductListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/setting': typeof SettingRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/setting/appearance': typeof SettingAppearanceRoute
  '/setting/categories': typeof SettingCategoriesRoute
  '/setting/export': typeof SettingExportRoute
  '/setting/profile': typeof SettingProfileRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/product/add': typeof appProductAddRoute
  '/(app)/product/list': typeof appProductListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/setting'
    | '/auth/login'
    | '/auth/signup'
    | '/setting/appearance'
    | '/setting/categories'
    | '/setting/export'
    | '/setting/profile'
    | '/'
    | '/product/add'
    | '/product/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/setting'
    | '/auth/login'
    | '/auth/signup'
    | '/setting/appearance'
    | '/setting/categories'
    | '/setting/export'
    | '/setting/profile'
    | '/'
    | '/product/add'
    | '/product/list'
  id:
    | '__root__'
    | '/(app)'
    | '/auth'
    | '/setting'
    | '/auth/login'
    | '/auth/signup'
    | '/setting/appearance'
    | '/setting/categories'
    | '/setting/export'
    | '/setting/profile'
    | '/(app)/'
    | '/(app)/product/add'
    | '/(app)/product/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SettingRouteRoute: typeof SettingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/setting/profile': {
      id: '/setting/profile'
      path: '/profile'
      fullPath: '/setting/profile'
      preLoaderRoute: typeof SettingProfileRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/export': {
      id: '/setting/export'
      path: '/export'
      fullPath: '/setting/export'
      preLoaderRoute: typeof SettingExportRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/categories': {
      id: '/setting/categories'
      path: '/categories'
      fullPath: '/setting/categories'
      preLoaderRoute: typeof SettingCategoriesRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/setting/appearance': {
      id: '/setting/appearance'
      path: '/appearance'
      fullPath: '/setting/appearance'
      preLoaderRoute: typeof SettingAppearanceRouteImport
      parentRoute: typeof SettingRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(app)/product/list': {
      id: '/(app)/product/list'
      path: '/product/list'
      fullPath: '/product/list'
      preLoaderRoute: typeof appProductListRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/product/add': {
      id: '/(app)/product/add'
      path: '/product/add'
      fullPath: '/product/add'
      preLoaderRoute: typeof appProductAddRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appIndexRoute: typeof appIndexRoute
  appProductAddRoute: typeof appProductAddRoute
  appProductListRoute: typeof appProductListRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appIndexRoute: appIndexRoute,
  appProductAddRoute: appProductAddRoute,
  appProductListRoute: appProductListRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SettingRouteRouteChildren {
  SettingAppearanceRoute: typeof SettingAppearanceRoute
  SettingCategoriesRoute: typeof SettingCategoriesRoute
  SettingExportRoute: typeof SettingExportRoute
  SettingProfileRoute: typeof SettingProfileRoute
}

const SettingRouteRouteChildren: SettingRouteRouteChildren = {
  SettingAppearanceRoute: SettingAppearanceRoute,
  SettingCategoriesRoute: SettingCategoriesRoute,
  SettingExportRoute: SettingExportRoute,
  SettingProfileRoute: SettingProfileRoute,
}

const SettingRouteRouteWithChildren = SettingRouteRoute._addFileChildren(
  SettingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SettingRouteRoute: SettingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
